### ISSUE TITLE
Linuxhosting API-calls partly working

### ISSUE THREAD

**Issue by sanderpotjer** [combell-nl/combell-api#2]
Working:
`/v2/linuxhostings/domainname.nl`

Not working (404 response):
`/v2/linuxhostings/domainname.nl/phpsettings/availableversions`

Empty response:
`/v2/linuxhostings`

So I do see the hosting details for the domain, but can't get the php versions and the list of all linuxhostings is emtpy for us.

**Comment by ibrambe** [comment]
We can't offer support for the api itself here, because this repo is only about the php authentication wrapper. I suggest you contact the support department via https://www.combell.nl/over-combell/contact.
